
services:
  ebac-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    volumes:
      - C:\Users\Nicholas\Documents\PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-ebac-network
      
  ebac-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ebac-projetos@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - ebac-postgres-compose
    networks:
      - postgres-ebac-network

networks: 
  postgres-ebac-network:
    driver: bridge